### ISSUE TITLE
Core Assets Version Mismatch

### ISSUE THREAD

**Issue by mikedilger** [pniekamp/datum#3]
Now I get a "Core Assets Version Mismatch" at runtime.
If I remove that check from the code, I get a segmentation fault.

**Comment by pniekamp** [comment]
I suspect last time I committed I didn't update the binaries, hence the core pack in the repo is older than the source code. 

The core.pack file is a generated file, outputted by the assetbuilder (contains the shader bytecode etc) and you could try to get that working, which you may need if you want to change any of the shaders.

In the short term, I've attached a version here that may be the one you need. (My code has moved on a little, so I'm not 100% sure everything lines up :(

[core.zip](https://github.com/pniekamp/datum/files/798261/core.zip)

Cheers

**Comment by pniekamp** [comment]
I have now synced up the repo with a new version, including the binaries. That should bring the source and the pack file versions in sync.

The newest version fixes some linux specific shader issues with the water surfaces and fog, which you might run into with the older pack file.

Cheers
-Peter
