### ISSUE TITLE
Can't launch datumtest

### ISSUE THREAD

**Issue by RayaneLehnemann** [pniekamp/datum#4]
Hello!

I have a problem, i can't lunch the datumtest, i am using a PC with a APU A10 7890k and a GPU Radeon R7, but when i try to run the datum, he give-me the following error:

![datum](https://user-images.githubusercontent.com/7956669/27113657-9418021a-5094-11e7-83e1-55ea14e10b68.png)

I am running normally all the Sascha Willems samples, and any other vulkan aplications like Xenko Game Engine or any other LunarG examples, but i can't run the Datum.

**Comment by pniekamp** [comment]
Hi Rodrigo,

I must admit that the renderer has really only been tested on an nvidia card. That said, I would be interested in seeing how well an amd card would work.

The problem you're seeing looks like an insufficient number of queues available on the R7. The renderer itself doesn't require multiple queues, but the test harness is using a separate transfer queue for background texture/mesh uploads (I am pushing highly multithreaded test cases to see how things pan out)

I've attached a version of the test program that still uses a separate transfer queue, but on a second queue family (which I think that card supports). If you are interested give it a run and see if you get any further. I sort of expect you will just hit another bug down the line, but I'd be interested in how it goes.

[test.zip](https://github.com/pniekamp/datum/files/1073503/test.zip)

Cheers
-Peter

**Comment by RayaneLehnemann** [comment]
Okay, you are right :)

The queue bug are solved, but i found a another bug:

![datum](https://user-images.githubusercontent.com/7956669/27134920-95feb282-50ed-11e7-8d4c-4ea711016c7e.png)

Maybe a thread error? Trying to read something are not defined yet?

Sorry for my poor english

**Comment by RayaneLehnemann** [comment]
If you can see i have two GPU cards, one is a dedicated GPU (R7 250) and another is a internal APU with a R7 graphics, in all vulkan application only the APU card are running. 

https://www.youtube.com/watch?v=ER_u3yLccBU

**Comment by pniekamp** [comment]
Well I'd call that progress anyway.

Not a thread error (yet). It looks to be an issue with the minStorageBufferOffsetAlignment returned by the card being smaller than I had expected. I have found dealing with the multitude of alignment requirements to be one of the tougher corners of Vulkan. A simple fix anyway, to just bound the alignment to be no less than 16. I've attached another test if you would like to try it.

I have also included a variant of the test that should try to use the second gpu in your system. I expect the results to be similar, but worth a try.

[test2.zip](https://github.com/pniekamp/datum/files/1076178/test2.zip)

Cheers
-Peter

Ps. and your english is great !

**Comment by RayaneLehnemann** [comment]
Okay, we have made a progress here, but we don't have a sucesseful render yet.
Here is the current error, same into both variants of test.

![datum](https://user-images.githubusercontent.com/7956669/27160246-29b95e86-5149-11e7-8abe-6913ef7a8463.png)

About the second GPU, here we need look for one specific detail, the second GPU don't have video output, he exist only for crossfire support. But if we can access it, and use it as support for the APU, we will create a new way to process the crossfire, and we will beat the AMD inself ;)

**Comment by pniekamp** [comment]
I'm not sure what is going on with this one... maybe one of the image formats isn't supported.

Could you try enabling the validation layers and check for any further messages... you can do this by setting the following environment variable... just run this command from command prompt before running datumtest.

    set VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_standard_validation

-Peter

**Comment by RayaneLehnemann** [comment]
Yep! Exactly, one of image format are unsupported:
![datum](https://user-images.githubusercontent.com/7956669/27163773-1801222a-5160-11e7-9ba8-109b824495de.png)

**Comment by pniekamp** [comment]
Alright, well that is an easy fix also (so far we have been lucky :)

Cross your fingers, and give this one a whirl.

[test3.zip](https://github.com/pniekamp/datum/files/1076507/test3.zip)

**Comment by RayaneLehnemann** [comment]
ohhh yeaah man!

now everthing is working, but with one little and strange glitch.
![datum](https://user-images.githubusercontent.com/7956669/27256398-15509e08-538a-11e7-866c-37be6e123f49.png)

**Comment by pniekamp** [comment]
Sweet.

But that is a strange glitch. I notice the sprite overlay isn't showing, so that may be a clue as to the issue. 

The attached version shows sprites in red, that should tell me if the sprite pass is the problem or to look elsewhere.

[test4.zip](https://github.com/pniekamp/datum/files/1082989/test4.zip)

Cheers

**Comment by pniekamp** [comment]
The pipeline has changed heaps lately. I suspect it still needs testing on various hardware, but I'll close this issue for now and attempt to get my hands on an amd graphics card.
